[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = true

[config]
model = "openai/qwen/qwen3.6-35b-a3b-fp8"
fallback_models = []
custom_model_max_tokens = 32768
max_model_tokens = 32768
token_encoding = "cl100k_base"
response_language = "zh-TW"

[openai]
api_base = "https://ainexus.phison.com/api/external/v1"
key_env = "AI_NEXUUS_PAT"

[litellm]
drop_params = true

[jira]
jira_base_url = "https://jira.phison.com:8443"
jira_api_token_env = "JIRA_BENNY_BOT_PAT"

[github_app]
pr_commands = [
    "/describe --pr_description.publish_description_as_comment=true",
    "/improve",
    "/agentic_review"
]

handle_push_trigger = true
push_commands = [
    "/improve",
    "/agentic_review"
]

[review_agent]
enabled = true
publish_output = true
